#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'AnotherFakeApi' {
    Context 'Invoke-123TestSpecialTags' {
        It 'Test Invoke-123TestSpecialTags' {
            #$TestResult = Invoke-123TestSpecialTags -Client "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
