#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'StoreApi' {
    Context 'Invoke-DeleteOrder' {
        It 'Test Invoke-DeleteOrder' {
            #$TestResult = Invoke-DeleteOrder -OrderId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-Inventory' {
        It 'Test Get-Inventory' {
            #$TestResult = Get-Inventory
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-OrderById' {
        It 'Test Get-OrderById' {
            #$TestResult = Get-OrderById -OrderId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-PlaceOrder' {
        It 'Test Invoke-PlaceOrder' {
            #$TestResult = Invoke-PlaceOrder -Order "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
