#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Cultivar
No description available.
.OUTPUTS

Apple<PSCustomObject>
#>

function Initialize-Apple {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Cultivar}
    )

    Process {
        'Creating PSCustomObject: petstore => Apple' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "cultivar" = ${Cultivar}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Apple<PSCustomObject>

.DESCRIPTION

Convert from JSON to Apple<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Apple<PSCustomObject>
#>
function ConvertFrom-JsonToApple {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: petstore => Apple' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $AppleAdditionalProperties = @{}

        # check if Json contains properties not defined in Apple
        $AllProperties = ("cultivar")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $AppleAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "cultivar"))) { #optional property not found
            $Cultivar = $null
        } else {
            $Cultivar = $JsonParameters.PSobject.Properties["cultivar"].value
        }

        $PSO = [PSCustomObject]@{
            "cultivar" = ${Cultivar}
            "AdditionalProperties" = $AppleAdditionalProperties
        }

        return $PSO
    }

}

