#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Cultivar
No description available.
.PARAMETER Mealy
No description available.
.OUTPUTS

AppleReq<PSCustomObject>
#>

function Initialize-AppleReq {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Cultivar},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Mealy}
    )

    Process {
        'Creating PSCustomObject: petstore => AppleReq' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Cultivar) {
            throw "invalid value for 'Cultivar', 'Cultivar' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "cultivar" = ${Cultivar}
            "mealy" = ${Mealy}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AppleReq<PSCustomObject>

.DESCRIPTION

Convert from JSON to AppleReq<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AppleReq<PSCustomObject>
#>
function ConvertFrom-JsonToAppleReq {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: petstore => AppleReq' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $AppleReqAdditionalProperties = @{}

        # check if Json contains properties not defined in AppleReq
        $AllProperties = ("cultivar", "mealy")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $AppleReqAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'cultivar' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "cultivar"))) {
            throw "Error! JSON cannot be serialized due to the required property 'cultivar' missing."
        } else {
            $Cultivar = $JsonParameters.PSobject.Properties["cultivar"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "mealy"))) { #optional property not found
            $Mealy = $null
        } else {
            $Mealy = $JsonParameters.PSobject.Properties["mealy"].value
        }

        $PSO = [PSCustomObject]@{
            "cultivar" = ${Cultivar}
            "mealy" = ${Mealy}
            "AdditionalProperties" = $AppleReqAdditionalProperties
        }

        return $PSO
    }

}

