#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER ClassName
No description available.
.PARAMETER Color
No description available.
.PARAMETER Declawed
No description available.
.OUTPUTS

Cat<PSCustomObject>
#>

function Initialize-Cat {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ClassName},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Color} = "red",
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Declawed}
    )

    Process {
        'Creating PSCustomObject: petstore => Cat' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ClassName) {
            throw "invalid value for 'ClassName', 'ClassName' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "className" = ${ClassName}
            "color" = ${Color}
            "declawed" = ${Declawed}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Cat<PSCustomObject>

.DESCRIPTION

Convert from JSON to Cat<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Cat<PSCustomObject>
#>
function ConvertFrom-JsonToCat {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: petstore => Cat' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $CatAdditionalProperties = @{}

        # check if Json contains properties not defined in Cat
        $AllProperties = ("className", "color", "declawed")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $CatAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'className' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "className"))) {
            throw "Error! JSON cannot be serialized due to the required property 'className' missing."
        } else {
            $ClassName = $JsonParameters.PSobject.Properties["className"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "color"))) { #optional property not found
            $Color = $null
        } else {
            $Color = $JsonParameters.PSobject.Properties["color"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "declawed"))) { #optional property not found
            $Declawed = $null
        } else {
            $Declawed = $JsonParameters.PSobject.Properties["declawed"].value
        }

        $PSO = [PSCustomObject]@{
            "className" = ${ClassName}
            "color" = ${Color}
            "declawed" = ${Declawed}
            "AdditionalProperties" = $CatAdditionalProperties
        }

        return $PSO
    }

}

