#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Client
No description available.
.OUTPUTS

Client<PSCustomObject>
#>

function Initialize-Client {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Client}
    )

    Process {
        'Creating PSCustomObject: petstore => Client' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "client" = ${Client}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Client<PSCustomObject>

.DESCRIPTION

Convert from JSON to Client<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Client<PSCustomObject>
#>
function ConvertFrom-JsonToClient {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: petstore => Client' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $ClientAdditionalProperties = @{}

        # check if Json contains properties not defined in Client
        $AllProperties = ("client")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $ClientAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "client"))) { #optional property not found
            $Client = $null
        } else {
            $Client = $JsonParameters.PSobject.Properties["client"].value
        }

        $PSO = [PSCustomObject]@{
            "client" = ${Client}
            "AdditionalProperties" = $ClientAdditionalProperties
        }

        return $PSO
    }

}

