#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum EnumClass.

.DESCRIPTION

No description available.
#>

enum EnumClass {
    # enum value: "_abc"
    _abc
    # enum value: "-efg"
    _efg
    # enum value: "(xyz)"
    _xyz
}

