#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Must be named `File` for test.

.PARAMETER SourceURI
Test capitalization
.OUTPUTS

File<PSCustomObject>
#>

function Initialize-File {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SourceURI}
    )

    Process {
        'Creating PSCustomObject: petstore => File' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "sourceURI" = ${SourceURI}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to File<PSCustomObject>

.DESCRIPTION

Convert from JSON to File<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

File<PSCustomObject>
#>
function ConvertFrom-JsonToFile {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: petstore => File' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $FileAdditionalProperties = @{}

        # check if Json contains properties not defined in File
        $AllProperties = ("sourceURI")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $FileAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "sourceURI"))) { #optional property not found
            $SourceURI = $null
        } else {
            $SourceURI = $JsonParameters.PSobject.Properties["sourceURI"].value
        }

        $PSO = [PSCustomObject]@{
            "sourceURI" = ${SourceURI}
            "AdditionalProperties" = $FileAdditionalProperties
        }

        return $PSO
    }

}

