#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER File
No description available.
.PARAMETER Files
No description available.
.OUTPUTS

FileSchemaTestClass<PSCustomObject>
#>

function Initialize-FileSchemaTestClass {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${File},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Files}
    )

    Process {
        'Creating PSCustomObject: petstore => FileSchemaTestClass' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "file" = ${File}
            "files" = ${Files}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to FileSchemaTestClass<PSCustomObject>

.DESCRIPTION

Convert from JSON to FileSchemaTestClass<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

FileSchemaTestClass<PSCustomObject>
#>
function ConvertFrom-JsonToFileSchemaTestClass {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: petstore => FileSchemaTestClass' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $FileSchemaTestClassAdditionalProperties = @{}

        # check if Json contains properties not defined in FileSchemaTestClass
        $AllProperties = ("file", "files")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $FileSchemaTestClassAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "file"))) { #optional property not found
            $File = $null
        } else {
            $File = $JsonParameters.PSobject.Properties["file"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "files"))) { #optional property not found
            $Files = $null
        } else {
            $Files = $JsonParameters.PSobject.Properties["files"].value
        }

        $PSO = [PSCustomObject]@{
            "file" = ${File}
            "files" = ${Files}
            "AdditionalProperties" = $FileSchemaTestClassAdditionalProperties
        }

        return $PSO
    }

}

