#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Bar
No description available.
.PARAMETER Foo
No description available.
.OUTPUTS

HasOnlyReadOnly<PSCustomObject>
#>

function Initialize-HasOnlyReadOnly {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Bar},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Foo}
    )

    Process {
        'Creating PSCustomObject: petstore => HasOnlyReadOnly' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "bar" = ${Bar}
            "foo" = ${Foo}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to HasOnlyReadOnly<PSCustomObject>

.DESCRIPTION

Convert from JSON to HasOnlyReadOnly<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

HasOnlyReadOnly<PSCustomObject>
#>
function ConvertFrom-JsonToHasOnlyReadOnly {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: petstore => HasOnlyReadOnly' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $HasOnlyReadOnlyAdditionalProperties = @{}

        # check if Json contains properties not defined in HasOnlyReadOnly
        $AllProperties = ("bar", "foo")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $HasOnlyReadOnlyAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bar"))) { #optional property not found
            $Bar = $null
        } else {
            $Bar = $JsonParameters.PSobject.Properties["bar"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "foo"))) { #optional property not found
            $Foo = $null
        } else {
            $Foo = $JsonParameters.PSobject.Properties["foo"].value
        }

        $PSO = [PSCustomObject]@{
            "bar" = ${Bar}
            "foo" = ${Foo}
            "AdditionalProperties" = $HasOnlyReadOnlyAdditionalProperties
        }

        return $PSO
    }

}

