#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Just a string to inform instance is up and running. Make it nullable in hope to get it as pointer in generated model.

.PARAMETER NullableMessage
No description available.
.OUTPUTS

HealthCheckResult<PSCustomObject>
#>

function Initialize-HealthCheckResult {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${NullableMessage}
    )

    Process {
        'Creating PSCustomObject: petstore => HealthCheckResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "NullableMessage" = ${NullableMessage}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to HealthCheckResult<PSCustomObject>

.DESCRIPTION

Convert from JSON to HealthCheckResult<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

HealthCheckResult<PSCustomObject>
#>
function ConvertFrom-JsonToHealthCheckResult {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: petstore => HealthCheckResult' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $HealthCheckResultAdditionalProperties = @{}

        # check if Json contains properties not defined in HealthCheckResult
        $AllProperties = ("NullableMessage")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $HealthCheckResultAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "NullableMessage"))) { #optional property not found
            $NullableMessage = $null
        } else {
            $NullableMessage = $JsonParameters.PSobject.Properties["NullableMessage"].value
        }

        $PSO = [PSCustomObject]@{
            "NullableMessage" = ${NullableMessage}
            "AdditionalProperties" = $HealthCheckResultAdditionalProperties
        }

        return $PSO
    }

}

