#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Uuid
No description available.
.PARAMETER DateTime
No description available.
.PARAMETER Map
No description available.
.OUTPUTS

MixedPropertiesAndAdditionalPropertiesClass<PSCustomObject>
#>

function Initialize-MixedPropertiesAndAdditionalPropertiesClass {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Uuid},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[System.DateTime]]
        ${DateTime},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [System.Collections.Hashtable]
        ${Map}
    )

    Process {
        'Creating PSCustomObject: petstore => MixedPropertiesAndAdditionalPropertiesClass' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "uuid" = ${Uuid}
            "dateTime" = ${DateTime}
            "map" = ${Map}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to MixedPropertiesAndAdditionalPropertiesClass<PSCustomObject>

.DESCRIPTION

Convert from JSON to MixedPropertiesAndAdditionalPropertiesClass<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

MixedPropertiesAndAdditionalPropertiesClass<PSCustomObject>
#>
function ConvertFrom-JsonToMixedPropertiesAndAdditionalPropertiesClass {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: petstore => MixedPropertiesAndAdditionalPropertiesClass' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $MixedPropertiesAndAdditionalPropertiesClassAdditionalProperties = @{}

        # check if Json contains properties not defined in MixedPropertiesAndAdditionalPropertiesClass
        $AllProperties = ("uuid", "dateTime", "map")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $MixedPropertiesAndAdditionalPropertiesClassAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "uuid"))) { #optional property not found
            $Uuid = $null
        } else {
            $Uuid = $JsonParameters.PSobject.Properties["uuid"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dateTime"))) { #optional property not found
            $DateTime = $null
        } else {
            $DateTime = $JsonParameters.PSobject.Properties["dateTime"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "map"))) { #optional property not found
            $Map = $null
        } else {
            $Map = $JsonParameters.PSobject.Properties["map"].value
        }

        $PSO = [PSCustomObject]@{
            "uuid" = ${Uuid}
            "dateTime" = ${DateTime}
            "map" = ${Map}
            "AdditionalProperties" = $MixedPropertiesAndAdditionalPropertiesClassAdditionalProperties
        }

        return $PSO
    }

}

