#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Model for testing reserved words

.PARAMETER VarReturn
No description available.
.OUTPUTS

ModelReturn<PSCustomObject>
#>

function Initialize-ModelReturn {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${VarReturn}
    )

    Process {
        'Creating PSCustomObject: petstore => ModelReturn' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "return" = ${VarReturn}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ModelReturn<PSCustomObject>

.DESCRIPTION

Convert from JSON to ModelReturn<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ModelReturn<PSCustomObject>
#>
function ConvertFrom-JsonToModelReturn {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: petstore => ModelReturn' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $ModelReturnAdditionalProperties = @{}

        # check if Json contains properties not defined in ModelReturn
        $AllProperties = ("return")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $ModelReturnAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "return"))) { #optional property not found
            $VarReturn = $null
        } else {
            $VarReturn = $JsonParameters.PSobject.Properties["return"].value
        }

        $PSO = [PSCustomObject]@{
            "return" = ${VarReturn}
            "AdditionalProperties" = $ModelReturnAdditionalProperties
        }

        return $PSO
    }

}

