#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Child
No description available.
.OUTPUTS

NullableAllOf<PSCustomObject>
#>

function Initialize-NullableAllOf {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Child}
    )

    Process {
        'Creating PSCustomObject: petstore => NullableAllOf' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "child" = ${Child}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to NullableAllOf<PSCustomObject>

.DESCRIPTION

Convert from JSON to NullableAllOf<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

NullableAllOf<PSCustomObject>
#>
function ConvertFrom-JsonToNullableAllOf {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: petstore => NullableAllOf' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $NullableAllOfAdditionalProperties = @{}

        # check if Json contains properties not defined in NullableAllOf
        $AllProperties = ("child")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $NullableAllOfAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "child"))) { #optional property not found
            $Child = $null
        } else {
            $Child = $JsonParameters.PSobject.Properties["child"].value
        }

        $PSO = [PSCustomObject]@{
            "child" = ${Child}
            "AdditionalProperties" = $NullableAllOfAdditionalProperties
        }

        return $PSO
    }

}

