#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER JustNumber
No description available.
.OUTPUTS

NumberOnly<PSCustomObject>
#>

function Initialize-NumberOnly {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Decimal]]
        ${JustNumber}
    )

    Process {
        'Creating PSCustomObject: petstore => NumberOnly' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "JustNumber" = ${JustNumber}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to NumberOnly<PSCustomObject>

.DESCRIPTION

Convert from JSON to NumberOnly<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

NumberOnly<PSCustomObject>
#>
function ConvertFrom-JsonToNumberOnly {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: petstore => NumberOnly' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json
        $NumberOnlyAdditionalProperties = @{}

        # check if Json contains properties not defined in NumberOnly
        $AllProperties = ("JustNumber")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            # store undefined properties in additionalProperties
            if (!($AllProperties.Contains($name))) {
                $NumberOnlyAdditionalProperties[$name] = $JsonParameters.PSobject.Properties[$name].value
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "JustNumber"))) { #optional property not found
            $JustNumber = $null
        } else {
            $JustNumber = $JsonParameters.PSobject.Properties["JustNumber"].value
        }

        $PSO = [PSCustomObject]@{
            "JustNumber" = ${JustNumber}
            "AdditionalProperties" = $NumberOnlyAdditionalProperties
        }

        return $PSO
    }

}

