#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'ApiResponse' {
    Context 'ApiResponse' {
        It 'Initialize-ApiResponse' {
            # a simple test to create an object
            #$NewObject = Initialize-ApiResponse -Code "TEST_VALUE" -Type "TEST_VALUE" -Message "TEST_VALUE"
            #$NewObject | Should -BeOfType ApiResponse
            #$NewObject.property | Should -Be 0
        }
    }
}
