#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'ArrayOfArrayOfNumberOnly' {
    Context 'ArrayOfArrayOfNumberOnly' {
        It 'Initialize-ArrayOfArrayOfNumberOnly' {
            # a simple test to create an object
            #$NewObject = Initialize-ArrayOfArrayOfNumberOnly -ArrayArrayNumber "TEST_VALUE"
            #$NewObject | Should -BeOfType ArrayOfArrayOfNumberOnly
            #$NewObject.property | Should -Be 0
        }
    }
}
