#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'Capitalization' {
    Context 'Capitalization' {
        It 'Initialize-Capitalization' {
            # a simple test to create an object
            #$NewObject = Initialize-Capitalization -SmallCamel "TEST_VALUE" -CapitalCamel "TEST_VALUE" -SmallSnake "TEST_VALUE" -CapitalSnake "TEST_VALUE" -SCAETHFlowPoints "TEST_VALUE" -ATTNAME "TEST_VALUE"
            #$NewObject | Should -BeOfType Capitalization
            #$NewObject.property | Should -Be 0
        }
    }
}
