#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'Dog' {
    Context 'Dog' {
        It 'Initialize-Dog' {
            # a simple test to create an object
            #$NewObject = Initialize-Dog -ClassName "TEST_VALUE" -Color "TEST_VALUE" -Breed "TEST_VALUE"
            #$NewObject | Should -BeOfType Dog
            #$NewObject.property | Should -Be 0
        }
    }
}
