#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'EnumTest' {
    Context 'EnumTest' {
        It 'Initialize-EnumTest' {
            # a simple test to create an object
            #$NewObject = Initialize-EnumTest -EnumString "TEST_VALUE" -EnumStringRequired "TEST_VALUE" -EnumInteger "TEST_VALUE" -EnumNumber "TEST_VALUE" -OuterEnum "TEST_VALUE" -OuterEnumInteger "TEST_VALUE" -OuterEnumDefaultValue "TEST_VALUE" -OuterEnumIntegerDefaultValue "TEST_VALUE"
            #$NewObject | Should -BeOfType EnumTest
            #$NewObject.property | Should -Be 0
        }
    }
}
