#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'Fruit' {
    Context 'Fruit' {
        It 'Initialize-Fruit' {
            # a simple test to create an object
            #$NewObject = Initialize-Fruit -Color "TEST_VALUE" -Cultivar "TEST_VALUE" -LengthCm "TEST_VALUE"
            #$NewObject | Should -BeOfType Fruit
            #$NewObject.property | Should -Be 0
        }
    }
}
