#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'MapTest' {
    Context 'MapTest' {
        It 'Initialize-MapTest' {
            # a simple test to create an object
            #$NewObject = Initialize-MapTest -MapMapOfString "TEST_VALUE" -MapOfEnumString "TEST_VALUE" -DirectMap "TEST_VALUE" -IndirectMap "TEST_VALUE"
            #$NewObject | Should -BeOfType MapTest
            #$NewObject.property | Should -Be 0
        }
    }
}
