#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'MixedPropertiesAndAdditionalPropertiesClass' {
    Context 'MixedPropertiesAndAdditionalPropertiesClass' {
        It 'Initialize-MixedPropertiesAndAdditionalPropertiesClass' {
            # a simple test to create an object
            #$NewObject = Initialize-MixedPropertiesAndAdditionalPropertiesClass -Uuid "TEST_VALUE" -DateTime "TEST_VALUE" -Map "TEST_VALUE"
            #$NewObject | Should -BeOfType MixedPropertiesAndAdditionalPropertiesClass
            #$NewObject.property | Should -Be 0
        }
    }
}
