#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'NumberOnly' {
    Context 'NumberOnly' {
        It 'Initialize-NumberOnly' {
            # a simple test to create an object
            #$NewObject = Initialize-NumberOnly -JustNumber "TEST_VALUE"
            #$NewObject | Should -BeOfType NumberOnly
            #$NewObject.property | Should -Be 0
        }
    }
}
