#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'OuterEnum' {
    Context 'OuterEnum' {
        It 'Initialize-OuterEnum' {
            # a simple test to create an object
            #$NewObject = Initialize-OuterEnum
            #$NewObject | Should -BeOfType OuterEnum
            #$NewObject.property | Should -Be 0
        }
    }
}
