#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'OuterEnumInteger' {
    Context 'OuterEnumInteger' {
        It 'Initialize-OuterEnumInteger' {
            # a simple test to create an object
            #$NewObject = Initialize-OuterEnumInteger
            #$NewObject | Should -BeOfType OuterEnumInteger
            #$NewObject.property | Should -Be 0
        }
    }
}
