#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'OuterComposite' {
    Context 'OuterComposite' {
        It 'Initialize-OuterComposite' {
            # a simple test to create an object
            #$NewObject = Initialize-OuterComposite -MyNumber "TEST_VALUE" -MyString "TEST_VALUE" -MyBoolean "TEST_VALUE"
            #$NewObject | Should -BeOfType OuterComposite
            #$NewObject.property | Should -Be 0
        }
    }
}
