#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'ReadOnlyFirst' {
    Context 'ReadOnlyFirst' {
        It 'Initialize-ReadOnlyFirst' {
            # a simple test to create an object
            #$NewObject = Initialize-ReadOnlyFirst -Bar "TEST_VALUE" -Baz "TEST_VALUE"
            #$NewObject | Should -BeOfType ReadOnlyFirst
            #$NewObject.property | Should -Be 0
        }
    }
}
