#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'ReadOnlyWithDefault' {
    Context 'ReadOnlyWithDefault' {
        It 'Initialize-ReadOnlyWithDefault' {
            # a simple test to create an object
            #$NewObject = Initialize-ReadOnlyWithDefault -Prop1 "TEST_VALUE" -Prop2 "TEST_VALUE" -Prop3 "TEST_VALUE" -BoolProp1 "TEST_VALUE" -BoolProp2 "TEST_VALUE" -IntProp1 "TEST_VALUE" -IntProp2 "TEST_VALUE"
            #$NewObject | Should -BeOfType ReadOnlyWithDefault
            #$NewObject.property | Should -Be 0
        }
    }
}
