#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'Tag' {
    Context 'Tag' {
        It 'Initialize-Tag' {
            # a simple test to create an object
            #$NewObject = Initialize-Tag -Id "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType Tag
            #$NewObject.property | Should -Be 0
        }
    }
}
