#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'User' {
    Context 'User' {
        It 'Initialize-User' {
            # a simple test to create an object
            #$NewObject = Initialize-User -Id "TEST_VALUE" -Username "TEST_VALUE" -FirstName "TEST_VALUE" -LastName "TEST_VALUE" -Email "TEST_VALUE" -Password "TEST_VALUE" -Phone "TEST_VALUE" -UserStatus "TEST_VALUE" -ArbitraryObject "TEST_VALUE" -ArbitraryNullableObject "TEST_VALUE" -ArbitraryTypeValue "TEST_VALUE" -ArbitraryNullableTypeValue "TEST_VALUE"
            #$NewObject | Should -BeOfType User
            #$NewObject.property | Should -Be 0
        }
    }
}
