#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'Whale' {
    Context 'Whale' {
        It 'Initialize-Whale' {
            # a simple test to create an object
            #$NewObject = Initialize-Whale -HasBaleen "TEST_VALUE" -HasTeeth "TEST_VALUE" -ClassName "TEST_VALUE"
            #$NewObject | Should -BeOfType Whale
            #$NewObject.property | Should -Be 0
        }
    }
}
