#
# OpenAPI Petstore
# This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: "" \
# Version: 1.0.0
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'petstore' -name 'Zebra' {
    Context 'Zebra' {
        It 'Initialize-Zebra' {
            # a simple test to create an object
            #$NewObject = Initialize-Zebra -Type "TEST_VALUE" -ClassName "TEST_VALUE"
            #$NewObject | Should -BeOfType Zebra
            #$NewObject.property | Should -Be 0
        }
    }
}
